# coding: utf-8

"""
    Kibernetika project, backend component

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.inference_api import InferenceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInferenceApi(unittest.TestCase):
    """InferenceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.inference_api.InferenceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inference_inference_version_delete(self):
        """Test case for inference_inference_version_delete

        Delete inference's version  # noqa: E501
        """
        pass

    def test_inference_inference_version_info(self):
        """Test case for inference_inference_version_info

        Return inference's info for specified version  # noqa: E501
        """
        pass

    def test_inference_inference_version_start(self):
        """Test case for inference_inference_version_start

        Starts serving  # noqa: E501
        """
        pass

    def test_inference_inference_version_update(self):
        """Test case for inference_inference_version_update

        Update inference's info for specified version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
