# coding: utf-8

"""
    Kibernetika project, backend component

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mlapp_images import MlappImages  # noqa: E501
from swagger_client.rest import ApiException


class TestMlappImages(unittest.TestCase):
    """MlappImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMlappImages(self):
        """Test MlappImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mlapp_images.MlappImages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
