# coding: utf-8

"""
    Kibernetika project, backend component

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1_host_path_volume_source import V1HostPathVolumeSource  # noqa: E501
from swagger_client.rest import ApiException


class TestV1HostPathVolumeSource(unittest.TestCase):
    """V1HostPathVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1HostPathVolumeSource(self):
        """Test V1HostPathVolumeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_host_path_volume_source.V1HostPathVolumeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
