# coding: utf-8

"""
    Kibernetika project, backend component

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from kclient.models.dealerclient_resource_limit import DealerclientResourceLimit  # noqa: F401,E501
from kclient.models.mlapp_resource_accelerators import MlappResourceAccelerators  # noqa: F401,E501


class MlappResourceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accelerators': 'MlappResourceAccelerators',
        'requests': 'DealerclientResourceLimit',
        'limits': 'DealerclientResourceLimit'
    }

    attribute_map = {
        'accelerators': 'accelerators',
        'requests': 'requests',
        'limits': 'limits'
    }

    def __init__(self, accelerators=None, requests=None, limits=None):  # noqa: E501
        """MlappResourceRequest - a model defined in Swagger"""  # noqa: E501

        self._accelerators = None
        self._requests = None
        self._limits = None
        self.discriminator = None

        self.accelerators = accelerators
        if requests is not None:
            self.requests = requests
        if limits is not None:
            self.limits = limits

    @property
    def accelerators(self):
        """Gets the accelerators of this MlappResourceRequest.  # noqa: E501


        :return: The accelerators of this MlappResourceRequest.  # noqa: E501
        :rtype: MlappResourceAccelerators
        """
        return self._accelerators

    @accelerators.setter
    def accelerators(self, accelerators):
        """Sets the accelerators of this MlappResourceRequest.


        :param accelerators: The accelerators of this MlappResourceRequest.  # noqa: E501
        :type: MlappResourceAccelerators
        """
        if accelerators is None:
            raise ValueError("Invalid value for `accelerators`, must not be `None`")  # noqa: E501

        self._accelerators = accelerators

    @property
    def requests(self):
        """Gets the requests of this MlappResourceRequest.  # noqa: E501


        :return: The requests of this MlappResourceRequest.  # noqa: E501
        :rtype: DealerclientResourceLimit
        """
        return self._requests

    @requests.setter
    def requests(self, requests):
        """Sets the requests of this MlappResourceRequest.


        :param requests: The requests of this MlappResourceRequest.  # noqa: E501
        :type: DealerclientResourceLimit
        """

        self._requests = requests

    @property
    def limits(self):
        """Gets the limits of this MlappResourceRequest.  # noqa: E501


        :return: The limits of this MlappResourceRequest.  # noqa: E501
        :rtype: DealerclientResourceLimit
        """
        return self._limits

    @limits.setter
    def limits(self, limits):
        """Sets the limits of this MlappResourceRequest.


        :param limits: The limits of this MlappResourceRequest.  # noqa: E501
        :type: DealerclientResourceLimit
        """

        self._limits = limits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MlappResourceRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MlappResourceRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
