# coding: utf-8

# flake8: noqa
"""
    Kibernetika project, backend component

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.dealerclient_resource_limit import DealerclientResourceLimit
from swagger_client.models.inference_run_serving_request import InferenceRunServingRequest
from swagger_client.models.mlapp_autoscale import MlappAutoscale
from swagger_client.models.mlapp_dataset_fs_source import MlappDatasetFSSource
from swagger_client.models.mlapp_dataset_source import MlappDatasetSource
from swagger_client.models.mlapp_env import MlappEnv
from swagger_client.models.mlapp_git_repo_volume_source import MlappGitRepoVolumeSource
from swagger_client.models.mlapp_images import MlappImages
from swagger_client.models.mlapp_model_source import MlappModelSource
from swagger_client.models.mlapp_persistent_storage import MlappPersistentStorage
from swagger_client.models.mlapp_port import MlappPort
from swagger_client.models.mlapp_resource_accelerators import MlappResourceAccelerators
from swagger_client.models.mlapp_resource_request import MlappResourceRequest
from swagger_client.models.mlapp_s3_bucket_source import MlappS3BucketSource
from swagger_client.models.mlapp_serving import MlappServing
from swagger_client.models.mlapp_serving_response_param import MlappServingResponseParam
from swagger_client.models.mlapp_serving_spec import MlappServingSpec
from swagger_client.models.mlapp_serving_spec_options import MlappServingSpecOptions
from swagger_client.models.mlapp_serving_spec_param import MlappServingSpecParam
from swagger_client.models.mlapp_serving_spec_param_value import MlappServingSpecParamValue
from swagger_client.models.mlapp_universal_serving import MlappUniversalServing
from swagger_client.models.mlapp_volume import MlappVolume
from swagger_client.models.mlapp_volume_mount import MlappVolumeMount
from swagger_client.models.models_inference_version import ModelsInferenceVersion
from swagger_client.models.models_serving import ModelsServing
from swagger_client.models.models_task_form_element import ModelsTaskFormElement
from swagger_client.models.models_task_form_element_stream_extended import ModelsTaskFormElementStreamExtended
from swagger_client.models.models_task_form_element_value import ModelsTaskFormElementValue
from swagger_client.models.v1_empty_dir_volume_source import V1EmptyDirVolumeSource
from swagger_client.models.v1_flex_volume_source import V1FlexVolumeSource
from swagger_client.models.v1_host_path_type import V1HostPathType
from swagger_client.models.v1_host_path_volume_source import V1HostPathVolumeSource
from swagger_client.models.v1_local_object_reference import V1LocalObjectReference
from swagger_client.models.v1_nfs_volume_source import V1NFSVolumeSource
from swagger_client.models.v1_persistent_volume_claim_volume_source import V1PersistentVolumeClaimVolumeSource
